---
title: "Schedule"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r, include=FALSE}
library(tidyverse)
library(here)
library(readxl)
library(glue)
library(downloadthis)
library(fontawesome)
library(gt)

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

table_style <- function(data) {
  data %>%
    opt_table_lines(extent = "none") %>%
    opt_table_outline(style = "solid", width = px(3), color = "black") %>% 
    tab_options(
      heading.border.bottom.color = "black",
      heading.border.bottom.style = "solid",
      table.border.top.color = "black",
      table_body.hlines.color = "black",
      table_body.border.top.color = "black",
      table_body.border.top.style = "solid",
      table_body.border.bottom.color = "black",
      table_body.border.bottom.style = "solid",
      column_labels.border.bottom.color = "black",
      column_labels.border.bottom.style = "solid",
      column_labels.border.top.color = "black",
      column_labels.background.color = "#56B4E9",
      table.width = pct(100),
      container.width = pct(100)
    )
}

assign_links <- read_xlsx(here::here("nopublish", "schedule_updated.xlsx"), sheet = "schedule") %>%
  select(Assigned, assigned_link) %>%
  drop_na() %>% 
  filter(str_detect(Assigned, "Homework")) %>%
  mutate(link_assign = map2_chr(assigned_link, Assigned, 
                                ~paste0("\ ", xfun::embed_file(path = here("homeworks", .x), text = .y)))) %>%
  select(-assigned_link) 

due_links <- read_xlsx(here::here("nopublish", "schedule_updated.xlsx"), sheet = "schedule") %>%
  select(Due, due_link) %>%
  drop_na() %>% 
  filter(str_detect(Due, "Homework")) %>%
  mutate(link_due = map2_chr(due_link, Due, 
                             ~paste0("\ ", xfun::embed_file(path = here("homeworks", .x), text = .y)))) %>%
  select(-due_link) 

sched_1 <- read_xlsx(here::here("nopublish", "schedule_updated.xlsx"), sheet = "schedule") %>% 
  mutate(
    Reading = paste0(Reading, "(", reading_link, ")"),
    Slides = paste0(Slides, "(", slides_link, ")"),
    Lecture = paste0(Lecture, "(", lecture_link, ")"),
    Assigned = ifelse(str_detect(Assigned, "Homework"), 
                      Assigned,
                      paste0(Assigned, "(", assigned_link, ")")),
    Due = ifelse(str_detect(Due, "Homework"), 
                 Due,
                 paste0(Due, "(", due_link, ")")),
    Date = format(as.Date(Date), "%b-%d")
  ) %>% 
  select(-ends_with("link"), -ends_with("shortcut"), -c(Topic, screenshot)) %>% 
  mutate(across(everything(), ~ifelse(. == "NA(NA)", NA_character_, .))) %>% 
  mutate(Lecture = ifelse(str_detect(Lecture, "fas"), Lecture, NA_character_)) %>% 
  mutate(across(everything(), ~str_remove(., "\\(NA\\)")))  


sched <- left_join(sched_1, assign_links) %>%
  left_join(due_links) %>% 
  mutate(
    Assigned = case_when(
      str_detect(Assigned, "Homework") & str_detect(link_assign, "href") ~ link_assign, 
      TRUE ~ Assigned),
    Due = case_when(
      str_detect(Due, "Homework") & str_detect(link_due, "href") ~ link_due, 
      TRUE ~ Due)) %>%
  select(-c(link_assign, link_due)) %>% 
  nest(data = c(Date, Reading, Slides, Lecture, Assigned, Due, lecture_passcode)) %>% 
  mutate(lecture_passcode = map_chr(data, ~.$lecture_passcode[[1]]),
         data = map(data, ~select(., -lecture_passcode)))

tbl_fx <- function(n){
  sched %>% 
  slice(n) %>% 
  select(data) %>% 
  unnest(cols = c(data)) %>% 
  gt::gt() %>% 
  fmt_markdown(columns = c(Reading, Slides, Lecture, Assigned, Due)) %>% 
  fmt_missing(
    columns = everything(),
    missing_text = ""
  ) %>% 
  cols_label(
    Date = md("<i class='far fa-calendar'></i>")
  ) %>% 
  tab_footnote(
    footnote = paste0("Passcode: ", sched$lecture_passcode[[n]]),
    locations = cells_body(
      columns = Lecture, rows = 1)
  ) %>% 
  table_style()
}
```
<br>
<br>
<br>

## Week 1: Introduction

```{r}

tbl_fx(1) %>% 
  tab_footnote(
    footnote = md("This is a brief older version. For the longer, updated version, see [here](https://style.tidyverse.org/). You don’t need to read this longer version."),
    locations = cells_body(
      columns = Reading, rows = 1)
  ) %>% 
  tab_footnote(
    footnote = "I do not rearrange my RStudio panes as he does.",
    locations = cells_body(
      columns = Assigned, rows = 1)
  ) 
```
<br>
<br>
<br>

## Week 2: Workflow

```{r}

tbl_fx(2)
```
<br>
<br>
<br>

## Week 3: `{ggplot2}`

```{r}
tbl_fx(3)
```
<br>
<br>
<br>

## Week 4: `{dplyr}`

```{r}
tbl_fx(4)
```
<br>
<br>
<br>

## Week 5: RMarkdown

```{r}
tbl_fx(5)
```
<br>
<br>
<br>

## Week 6: GitHub

```{r}
tbl_fx(6)
```
<br>
<br>
<br>

## Week 7: Mutating Joins

```{r}
tbl_fx(7)
```
<br>
<br>
<br>

## Week 8: Tidy Data

```{r}
tbl_fx(8)
```
<br>
<br>
<br>

## Week 9: Factors & Pull Request

```{r}
tbl_fx(9)
```
<br>
<br>
<br>

## Week 10: Presentations

```{r}
tbl_fx(10)
```
<br>
<br>
<br>

## Week 11: No class: Final papers due

